In [60]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv('sales.csv')

READ THE DATA

In [62]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

CHECKING THE DATA

In [93]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1000555,Tea,1,1.5,1.5,Credit Card,In-store,2023-10-19
1,TXN_1002457,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-09-29
2,TXN_1004184,Smoothie,1,4.0,4.0,Credit Card,In-store,2023-05-18
3,TXN_1004563,Tea,5,1.5,7.5,Credit Card,In-store,2023-10-28
4,TXN_1005331,Coffee,1,2.0,2.0,Digital Wallet,Takeaway,2023-11-04

CHECKING THE FIRST FIVE ROW

In [64]:
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

CHECKING THE LAST FIVE ROWS

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [66]:
df.isna().sum().sum()

np.int64(6826)

CHECKING TOTAL NaN IN THE DATA

In [67]:
df = df.dropna()

CLEANING ALL NaN

In [68]:
df.isna().sum().sum()

np.int64(0)

CHECKING IF ANY NaN ARE FOUND

In [69]:
df.duplicated().sum()

np.int64(0)

CHECKING FOR DUPLICATES

In [70]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

REMOVING VALUES & CHANGING THE DATA TYPES

In [94]:
pd.Series(df['Transaction ID'].unique().tolist()).str.startswith('TXN').value_counts()

True    3089
Name: count, dtype: int64

COUNTING UNIQUE VALUES

In [99]:
df['Item'].unique()

<StringArray>
['Tea', 'Cookie', 'Smoothie', 'Coffee', 'Salad', 'Cake', 'Sandwich', 'Juice']
Length: 8, dtype: str

FOUND THIS TWO 'UNKNOWN' 'ERROR' IN THE DATA

In [73]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='str')

In [74]:
df=df[~df.isin(['UNKNOWN','ERROR']).any(axis=1)]

REMOVING THOSE TWO VALUES FROM DATA

In [75]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
...,...,...,...,...,...,...,...,...
9975,TXN_9668108,Cake,1,3.0,3.0,Cash,In-store,2023-01-20
9979,TXN_9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [76]:
df['Quantity'] = df['Quantity'].astype(int)

In [77]:
df['Price Per Unit']=df['Price Per Unit'].astype(float)
df['Total Spent']=df['Total Spent'].astype(float)

CONVERTING COLUMN TO INTEGER AND FLOATS

In [78]:
df.dtypes

Transaction ID          str
Item                    str
Quantity              int64
Price Per Unit      float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
dtype: object

CHECKING DATATYPES

In [79]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
...,...,...,...,...,...,...,...,...
9975,TXN_9668108,Cake,1,3.0,3.0,Cash,In-store,2023-01-20
9979,TXN_9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [80]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

CHANGING THIS COLUMN TO DATETIME

In [81]:
df.dtypes

Transaction ID                 str
Item                           str
Quantity                     int64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
dtype: object

In [82]:
df = df.sort_values('Transaction ID').reset_index(drop=True)

In [83]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1000555,Tea,1,1.5,1.5,Credit Card,In-store,2023-10-19
1,TXN_1002457,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-09-29
2,TXN_1004184,Smoothie,1,4.0,4.0,Credit Card,In-store,2023-05-18
3,TXN_1004563,Tea,5,1.5,7.5,Credit Card,In-store,2023-10-28
4,TXN_1005331,Coffee,1,2.0,2.0,Digital Wallet,Takeaway,2023-11-04
...,...,...,...,...,...,...,...,...
3084,TXN_9989719,Smoothie,2,4.0,8.0,Credit Card,Takeaway,2023-11-26
3085,TXN_9991225,Cake,5,3.0,15.0,Credit Card,Takeaway,2023-02-03
3086,TXN_9992148,Tea,3,1.5,4.5,Cash,Takeaway,2023-01-14
3087,TXN_9996195,Juice,5,3.0,15.0,Digital Wallet,In-store,2023-03-16
3088,TXN_9999113,Juice,4,3.0,12.0,Cash,Takeaway,2023-05-27

In [86]:
df.to_csv('sales_cleaned.csv', index = False)

In [91]:
df.to_excel('sales_cleaned_excel.xlsx', index = False)